In [109]:
import pandas
import numpy as np

In [10]:
loan_result = pandas.read_csv('/Users/parksimon/Desktop/loan_result.csv')
log_data = pandas.read_csv('/Users/parksimon/Desktop/log_data.csv')
user_spec = pandas.read_csv('/Users/parksimon/Desktop/user_spec.csv')

In [23]:
not_nan = loan_result[loan_result['is_applied'].notnull()]
not_nan

application_id loanapply_insert_time  bank_id  product_id  \
13284            2157865   2022-05-09 08:44:59       54         235   
13285             576643   2022-05-09 10:54:53       54         235   
13286             576643   2022-05-09 10:54:53       11         118   
13287            2136706   2022-05-09 10:41:06       42         216   
13288            2136706   2022-05-09 10:41:07       25         169   
...                  ...                   ...      ...         ...   
13519634         1969227   2022-05-16 14:42:58        2           7   
13519635         1969227   2022-05-16 14:42:57       33         110   
13519636         1969227   2022-05-16 14:42:56       50         142   
13519637         1969227   2022-05-16 14:43:18       22         100   
13519638         1969227   2022-05-16 14:42:56       19         231   

          loan_limit  loan_rate  is_applied  
13284     20000000.0       16.5         1.0  
13285     11000000.0       16.5         0.0  
13286      3000000.0       20.0         0.0  
13287     10000000.0       13.5         0.0  
13288     22000000.0       15.9         0.0  
...              ...        ...         ...  
13519634  30000000.0       13.6         0.0  
13519635   9000000.0       14.4         0.0  
13519636   3000000.0       11.2         0.0  
13519637   4000000.0       15.3         0.0  
13519638   9000000.0       15.5         0.0  

[10270124 rows x 7 columns]

In [35]:
sorted_nan = not_nan.sort_values(by='application_id')

sorted_spec = user_spec.sort_values(by='application_id')

In [81]:
sorted_nan.head()

application_id loanapply_insert_time  bank_id  product_id  \
10972632               1   2022-05-06 11:05:42       59         150   
10972631               1   2022-05-06 11:05:43       50         142   
10972630               1   2022-05-06 11:05:44       37         206   
10972629               1   2022-05-06 11:05:43       38         223   
10972628               1   2022-05-06 11:05:56       38          16   

          loan_limit  loan_rate  is_applied  
10972632  19000000.0       17.7         0.0  
10972631  18000000.0       19.9         0.0  
10972630  32000000.0       18.9         0.0  
10972629  19000000.0       17.1         0.0  
10972628  19000000.0       17.1         0.0

In [82]:
sorted_spec.head()

application_id  user_id  birth_year  gender          insert_time  \
535078                1   777860      1990.0     1.0  2022-05-06 11:05:42   
705026                2    28169      1981.0     1.0  2022-04-13 10:57:03   
206459                3   492886      1955.0     1.0  2022-05-13 18:11:51   
359412                4   209531      1978.0     0.0  2022-06-20 10:24:36   
1236114               6    59078      1991.0     1.0  2022-04-26 02:02:44   

         credit_score  yearly_income   income_type  company_enter_month  \
535078          580.0     40000000.0  EARNEDINCOME             201702.0   
705026          590.0     43000000.0  EARNEDINCOME             201903.0   
206459          520.0     20000000.0    FREELANCER             201201.0   
359412          720.0     26000000.0  EARNEDINCOME           20100301.0   
1236114         630.0     36000000.0  EARNEDINCOME             202202.0   

        employment_type houseown_type  desired_amount purpose  \
535078              정규직           전월세      30000000.0    대환대출   
705026              정규직            자가      10000000.0     생활비   
206459               기타           전월세       3000000.0     생활비   
359412              정규직        기타가족소유      16000000.0     생활비   
1236114             정규직           전월세      36000000.0    대환대출   

         personal_rehabilitation_yn  personal_rehabilitation_complete_yn  \
535078                          0.0                                  0.0   
705026                          NaN                                  NaN   
206459                          0.0                                  NaN   
359412                          0.0                                  NaN   
1236114                         0.0                                  NaN   

         existing_loan_cnt  existing_loan_amt  
535078                 NaN                NaN  
705026                12.0        204000000.0  
206459                 4.0         66000000.0  
359412                 5.0         67000000.0  
1236114                4.0         72000000.0

In [113]:
tmp_df = pandas.merge(left=sorted_nan, right=sorted_spec, how="inner", on="application_id")

x_df = tmp_df.loc[:, ['loan_limit', 'loan_rate', 'credit_score', 'yearly_income', 'desired_amount']]
y_df = tmp_df.loc[:, ['is_applied']]

loan_limit  loan_rate  credit_score  yearly_income  desired_amount
0         19000000.0       17.7         580.0     40000000.0      30000000.0
1         18000000.0       19.9         580.0     40000000.0      30000000.0
2         32000000.0       18.9         580.0     40000000.0      30000000.0
3         19000000.0       17.1         580.0     40000000.0      30000000.0
4         19000000.0       17.1         580.0     40000000.0      30000000.0
...              ...        ...           ...            ...             ...
10270006  22000000.0       16.9         560.0     32000000.0       5000000.0
10270007  20000000.0       19.9         560.0     32000000.0       5000000.0
10270008  22000000.0       16.9         560.0     32000000.0       5000000.0
10270009   5000000.0       18.7         560.0     32000000.0       5000000.0
10270010  13000000.0       17.4         560.0     32000000.0       5000000.0

[10270011 rows x 5 columns]

In [121]:
x = x_df.to_numpy()
y = y_df.to_numpy()

In [122]:
print(x)

[[1.90e+07 1.77e+01 5.80e+02 4.00e+07 3.00e+07]
 [1.80e+07 1.99e+01 5.80e+02 4.00e+07 3.00e+07]
 [3.20e+07 1.89e+01 5.80e+02 4.00e+07 3.00e+07]
 ...
 [2.20e+07 1.69e+01 5.60e+02 3.20e+07 5.00e+06]
 [5.00e+06 1.87e+01 5.60e+02 3.20e+07 5.00e+06]
 [1.30e+07 1.74e+01 5.60e+02 3.20e+07 5.00e+06]]
